import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import { CatImg } from "../components/CatImg";
import { Loader } from "../components/Loader";
import { MainLayout } from "../layouts/MainLayout";

export async function getServerSideProps() {
  const res = await axios(`http://localhost:3000/api/cat-info`);
  const data = await res.data;
  return { props: { data } };
}

interface ICatData {
  name: string;
  age: string;
  type: string;
}

export default function CatPage({ data }: { data: ICatData }) {
  const [catImg, setCatImg] = useState<string | undefined>(undefined);

  useEffect(() => {
    axios.get(`http://localhost:3000/api/cat-img`).then((res) => setCatImg(res.data));
  }, []);

  return (
    <div className="min-h-[100vh] bg-slate-900 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="pl-4 font-medium text-slate-200">
          <h1>Cat page</h1>

          <div className="flex-col ml-0 pl-0">
            {Object.entries(data).map((info) => (
              <h2 className="pr-2" key={info.toString()}>
                {info[0]}: {info[1]}
              </h2>
            ))}
          </div>
          {catImg ? <CatImg url={catImg} /> : <Loader />}
        </div>
      </MainLayout>
    </div>
  );
}
