import Head from "next/head";
import { useEffect } from "react";
import { MainLayout } from "../layouts/MainLayout";

export default function Home() {
  return (
    <div className="min-h-[100vh] bg-slate-900">
      <Head>
        <title>Vahui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1>Home page</h1>
      </MainLayout>
    </div>
  );
}
