import Head from "next/head";
import Image from "next/image";
import { MainLayout } from "../layouts/MainLayout";

const MyContentA = () => <div className=" text-white border-2 border-green-300"> MyContent 1 </div>;
const MyContentB = () => <div className=" text-green-300 border-2 border-green-900"> MyContent 2 </div>;

export default function Home() {
  return (
    <div className="h-100 min-h-[100vh] bg-slate-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <MyContentA />
        <MyContentB />
      </MainLayout>
    </div>
  );
}
